name: 10x developers don't need old stuff

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  delete-old-actions:
    runs-on: ubuntu-latest
    name: Delete old 10x Actions
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: yanovation/delete-old-actions@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          days-ago: 14
